### ISSUE TITLE
make minidown support pipeline.

### ISSUE THREAD

**Issue by zw963** [jjyr/minidown#10]
嘿， this gem is very very COOL!

I hope can support pipeline, because my emacs markdown-mode need
text stream to be feed as STDIN, so, I hope mindown can support this.

following is some code you can refer to, thanks very much.

```ruby
if File.pipe?($stdin)
  puts Minidown.render($stdin.read)
  exit
end

file = ARGV.first
if file 
....
```

**Comment by jjyr** [comment]
哟, the `minidown` cmd already support linux pipeline, and `pipeline` feature is very easy to implement(few lines code just like u provided) by uself when u use minidown as library, it's unnecessary add this feature to this gem. 

PS: minidown has been unmantained 2 years, maybe includes some bugs, its recommanded as a tiny open source markdown parser to learn rather than to use
